name: Newman run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create folder for reports
        run: mkdir -p newman

      - name: Install Node.js
        uses: actions/setup-node@v3.4.1

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Tests with Newman
        run: |
          newman run ServeRest.postman_collection.json \
            -e serveResT_env.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/report.html

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Reports
          path: newman


      
    

    
